name: deploy-netlify

on:
  workflow_run:
    workflows: ["gh-pages"]
    types: [completed]

jobs:
  send:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy Netlify
        run: |
          curl -X POST -d {} https://api.netlify.com/build_hooks/6360259fadc55f24dd1dedc7
